# set(CMAKE_CXX_STANDARD 11)

set(CMAKE_CXX_STANDARD 11)
IF(OG_SAMPLE_ON)

set(COMMON 
	OgSample.h
	OgSample.cpp
	)
source_group("private" FILES ${COMMON})

list(APPEND TOTAL_FILE ${COMMON})

add_library(sample STATIC ${TOTAL_FILE})
link_directories(${LIB_DIR})
target_link_libraries(sample render)#${GLFW3}

IF(OG_ENGINE_SHARED_LIB)
	target_compile_definitions(sample PRIVATE "-DOG_API_EXPORT")
ENDIF()

## DEBUG
INSTALL(TARGETS sample CONFIGURATIONS Debug ARCHIVE DESTINATION "${INSTALL_FOLDER}/dev/lib" LIBRARY DESTINATION "${INSTALL_FOLDER}" RUNTIME DESTINATION "${INSTALL_FOLDER}")
install(DIRECTORY "." CONFIGURATIONS Debug PUBLIC_HEADER DESTINATION "${INSTALL_FOLDER}/dev/include/sample" FILES_MATCHING PATTERN "*.h" PATTERN "private" EXCLUDE)
install(FILES "../OgPrecompiled.h" CONFIGURATIONS Debug PUBLIC_HEADER DESTINATION "${INSTALL_FOLDER}/dev/include")


## RELEASE

install(TARGETS sample CONFIGURATIONS Release ARCHIVE DESTINATION "${INSTALL_FOLDER}/dev/lib")
install(DIRECTORY "." CONFIGURATIONS Release PUBLIC_HEADER DESTINATION "${INSTALL_FOLDER}/dev/include/sample" FILES_MATCHING PATTERN "*.h" PATTERN "private" EXCLUDE)
install(FILES "../OgPrecompiled.h" CONFIGURATIONS Release PUBLIC_HEADER DESTINATION "${INSTALL_FOLDER}/dev/include")
## RELWITHDEBINFO

install(TARGETS sample CONFIGURATIONS RelWithDebInfo ARCHIVE DESTINATION "${INSTALL_FOLDER}/dev/lib")
install(DIRECTORY "." CONFIGURATIONS RelWithDebInfo PUBLIC_HEADER DESTINATION "${INSTALL_FOLDER}/dev/include/sample" FILES_MATCHING PATTERN "*.h" PATTERN "private" EXCLUDE)
install(FILES "../OgPrecompiled.h" CONFIGURATIONS RelWithDebInfo PUBLIC_HEADER DESTINATION "${INSTALL_FOLDER}/dev/include")

## Common

# install(FILES ${CLANG_LIBS} DESTINATION "${INSTALL_FOLDER}")
# install(FILES ${RES_DIR}/imgui.ini CONFIGURATIONS Debug DESTINATION "${INSTALL_FOLDER}")

#if(SCRIPT_GENERATOR_PROJECT)
#	install(FILES $<TARGET_FILE_DIR:sample>/Editor-Script-Generator.exe CONFIGURATIONS Debug DESTINATION "${INSTALL_FOLDER}")
#	install(FILES $<TARGET_FILE_DIR:sample>/Editor-Script-Generator.exe CONFIGURATIONS Release DESTINATION "${INSTALL_FOLDER}")
#endif()
ENDIF()