# Reference :
# https://stackoverflow.com/questions/39807664/how-to-best-tell-cmake-where-to-find-dll


set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)


set(PUBLIC_COMMON 
)
source_group("public" FILES ${PUBLIC_COMMON})
list(APPEND TOTAL_FILE ${PUBLIC_COMMON})

set(PRIVATE_COMMON 
	private/OgMain.cpp
	# TODO
	)
source_group("private" FILES ${PRIVATE_COMMON})
list(APPEND TOTAL_FILE ${PRIVATE_COMMON})

set(PRIVATE_PANEL
	#private/panel/OgImGuiSamplePanel.cpp
	# TODO
	)

source_group("panel\\private" FILES ${PRIVATE_PANEL})
list(APPEND TOTAL_FILE ${PRIVATE_PANEL})


set(PUBLIC_PANEL
	#panel/OgImGuiSamplePanel.h
	)
source_group("panel\\public" FILES ${PUBLIC_PANEL})
list(APPEND TOTAL_FILE ${PUBLIC_PANEL})


add_executable(application ${TOTAL_FILE} )

IF(OG_ENGINE_SHARED_LIB)
	add_definitions("-DOG_API_EXPORT")
	# set_target_properties(sample PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON )
ENDIF()

#target_compile_definitions(application PRIVATE "-DIMGUI_INCLUDE_IMCONFIG_H" "-DLV_EDITOR_API_IMPORT" "-DLV_USER_API_IMPORT" "-DLV_EDITOR")


SET_TARGET_PROPERTIES(application PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${OG_PROJECT_BINARY_DIR})


link_directories(${LIB_DIR})

TARGET_LINK_OPTIONS(application PRIVATE "/WHOLEARCHIVE:render")


IF(OG_SAMPLE_ON)
	target_link_libraries(application render sample)
ELSE()
	target_link_libraries(application render)
ENDIF()



set_property(TARGET application PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_BINARY_DIR}")
set_property(TARGET application PROPERTY VS_DEBUGGER_COMMAND_ARGUMENTS "-g VULKAN")


set(RES_DIR ${PROJECT_SOURCE_DIR}/res)


set(PROGRAM_PERMISSIONS_DEFAULT
    OWNER_WRITE OWNER_READ OWNER_EXECUTE
    GROUP_READ GROUP_EXECUTE
    WORLD_READ WORLD_EXECUTE)

## DEBUG

install(TARGETS application CONFIGURATIONS Debug  DESTINATION "${INSTALL_FOLDER}" PERMISSIONS ${PROGRAM_PERMISSIONS_DEFAULT} SETUID)
install(DIRECTORY ${DLL_DEBUG_DIR}/ CONFIGURATIONS Debug DESTINATION "${INSTALL_FOLDER}")


#install(DIRECTORY ${RES_DIR}/icons CONFIGURATIONS Debug DESTINATION "${INSTALL_FOLDER}")
message(STATUS " - RES_DIR \t ${RES_DIR}")
install(DIRECTORY ${RES_DIR}/fonts CONFIGURATIONS Debug DESTINATION "${INSTALL_FOLDER}")
#install(DIRECTORY ${RES_DIR}/BuiltInShaders CONFIGURATIONS Debug DESTINATION "${INSTALL_FOLDER}")
message(STATUS " - PROJECT_SOURCE_DIR \t ${INSTALL_FOLDER}")

## RELEASE

install(TARGETS application CONFIGURATIONS Release DESTINATION "${INSTALL_FOLDER}" PERMISSIONS ${PROGRAM_PERMISSIONS_DEFAULT} SETUID)
install(DIRECTORY ${DLL_RELEASE_DIR}/ CONFIGURATIONS Release DESTINATION "${INSTALL_FOLDER}")

#install(DIRECTORY ${RES_DIR}/icons CONFIGURATIONS Release DESTINATION "${INSTALL_FOLDER}")
install(DIRECTORY ${RES_DIR}/fonts CONFIGURATIONS Release DESTINATION "${INSTALL_FOLDER}")
#install(DIRECTORY ${RES_DIR}/BuiltInShaders CONFIGURATIONS Release DESTINATION "${INSTALL_FOLDER}")

## RELWITHDEBINFO

install(TARGETS application CONFIGURATIONS RelWithDebInfo DESTINATION "${INSTALL_FOLDER}" PERMISSIONS ${PROGRAM_PERMISSIONS_DEFAULT} SETUID)
install(DIRECTORY ${DLL_RELEASE_DIR}/ CONFIGURATIONS RelWithDebInfo DESTINATION "${INSTALL_FOLDER}")

#install(DIRECTORY ${RES_DIR}/icons CONFIGURATIONS RelWithDebInfo DESTINATION "${INSTALL_FOLDER}")
install(DIRECTORY ${RES_DIR}/fonts CONFIGURATIONS RelWithDebInfo DESTINATION "${INSTALL_FOLDER}")
#install(DIRECTORY ${RES_DIR}/BuiltInShaders CONFIGURATIONS RelWithDebInfo DESTINATION "${INSTALL_FOLDER}")

# Common

# install(FILES ${CLANG_LIBS} DESTINATION "${INSTALL_FOLDER}")

install(FILES ${RES_DIR}/imgui.ini CONFIGURATIONS Debug DESTINATION "${INSTALL_FOLDER}")

#if(SCRIPT_GENERATOR_PROJECT)
#	install(FILES $<TARGET_FILE_DIR:application>/Editor-Script-Generator.exe CONFIGURATIONS Debug DESTINATION "${INSTALL_FOLDER}")
#	install(FILES $<TARGET_FILE_DIR:application>/Editor-Script-Generator.exe CONFIGURATIONS Release DESTINATION "${INSTALL_FOLDER}")
#endif()
